name: Deploy to Railway

on:
  push:
    branches:
      - main # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t myapp:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push myapp:latest

    - name: Deploy to Railway
      run: |
        curl -X POST https://api.railway.app/v1/projects/YOUR_PROJECT_ID/deployments \
        -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"image": "myapp:latest"}'
